config/routes.rb
Planet::Application.routes.draw do

  resources :sites
    
  resources :types
    
  resources :types do
    resources :sites
  end

  get "planet/index"

  get "planet/contact"

  get "planet/ejemplo"    # Se añade una nueva ruta a la acción ejemplo
    
  get "planet/author"

    
  root :to => "planet#index"
    

end

app/models/site.rb
class Site < ActiveRecord::Base
    belongs_to :type
    belongs_to :trip
    validates_presence_of :name, :message => "must be provided"
end

app/models/type.rb
class Type < ActiveRecord::Base
has_many:sites
end

app/models/viaje.rb
class Viaje < ActiveRecord::Base
has_many:site
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
  end

  def contact
  end

# GET /planet/ejemplo
  def ejemplo
  end
    
  def author
  end

end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  # GET /sites
  # GET /sites.json
  def index
    if params[:type_id].nil? or params[:type_id].empty?
      @sites = Site.all
    else
      @sites = Type.find(params[:type_id]).sites
    end
    @trip = Trip.new
    
    respond_to do |format|
      format.html # index.html.erb
        format.json { render :json=> @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    @site = Site.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
        format.json { render :json=> @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
        format.json { render :json=> @site }
    end
  end

  # GET /sites/1/edit
  def edit
    @site = Site.find(params[:id])
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])

    respond_to do |format|
      if @site.save
          format.html { redirect_to @site, :notice=> 'Site was successfully created.' }
          format.json { render :json=> @site, :status=> :created, :location=> @site }
      else
          format.html { render :action=> "new" }
          format.json { render :json=> @site.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    @site = Site.find(params[:id])

    respond_to do |format|
      if @site.update_attributes(params[:site])
          format.html { redirect_to @site, :notice=> 'Site was successfully updated.' }
        format.json { head :ok }
      else
          format.html { render :action=> "edit" }
          format.json { render :json=> @site.errors, :status=> :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site = Site.find(params[:id])
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :ok }
    end
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  # GET /types
  # GET /types.json
  def index
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @types }
    end
  end

  # GET /types/1
  # GET /types/1.json
  def show
    @type = Type.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @type }
    end
  end

  # GET /types/new
  # GET /types/new.json
  def new
    @type = Type.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @type }
    end
  end

  # GET /types/1/edit
  def edit
    @type = Type.find(params[:id])
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(params[:type])

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, :notice => 'Type was successfully created.' }
        format.json { render :json => @type, :status => :created, :location => @type }
      else
        format.html { render :action => "new" }
        format.json { render :json => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /types/1
  # PUT /types/1.json
  def update
    @type = Type.find(params[:id])

    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, :notice =>'Type was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @type.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type = Type.find(params[:id])
    @type.destroy

    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :ok }
    end
  end
end

app/controllers/viajes_controller.rb
class ViajesController < ApplicationController
  # GET /viajes
  # GET /viajes.json
  def index
    @viajes = Viaje.find(:all, :order =>"orden")
    @sitios = Site.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @viajes }
    end
  end

  # GET /viajes/1
  # GET /viajes/1.json
  def show
    @viaje = Viaje.find(params[:id])
    @sitio = Site.find(@viaje.site_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @viaje }
    end
  end

  # GET /viajes/new
  # GET /viajes/new.json
  def new
    @viaje = Viaje.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @viaje }
    end
  end

  # GET /viajes/1/edit
  def edit
    @viaje = Viaje.find(params[:id])
  end

  

# POST /viajes
  # POST /viajes.json


  def create
 @orden_sig = (Viaje.all.count+1)
if params[:site_id].nil? 
    @viaje = Viaje.new(params[:viaje])
else 
if params[:orden]==@orden_sig 
   @viaje = Viaje.new(params[:viaje])
else
  params[:orden]= @orden_sig 
@viaje = Viaje.new(params[:viaje])
 # @viaje = Viaje.new(:site_id =>params[:viaje][:site_id], :orden => (Viaje.all.count+1))
end
end
    respond_to do |format|
      if @viaje.save
        format.html { redirect_to @viaje, notice: 'Viaje was successfully created. Order: '+ @orden_sig.to_s }
        format.json { render json: @viaje, status: :created, location: @viaje }
      else
        format.html { render action: "new" }
        format.json { render json: @viaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /viajes/1
  # PUT /viajes/1.json
  def update
#if params[:site_id]!=nil #si site_id no es nil ... 
@orden_new = params[:viaje][:orden]    
@orden_old = params[:viaje][:orden_old]
    @viaje_old = Viaje.find_by_orden(@orden_new)
    @viaje = Viaje.find(params[:id]) #al que modifico pongo orden que me envian y al viaje_old le pongo el orden del actual
    
    respond_to do |format|
  if (@viaje.update_attributes(:orden => @orden_new) and @viaje_old.update_attributes(:orden => @orden_old))
 #      if @viaje.update_attributes(params[:viaje])
        format.html { redirect_to @viaje, notice: 'Viaje was successfully updated. Order Changed--> ' + 'new order: '+@orden_new.to_s}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @viaje.errors, status: :unprocessable_entity }
      end
    end

 
end

  # DELETE /viajes/1
  # DELETE /viajes/1.json
  def destroy
    @viaje = Viaje.find(params[:id])
    @orden = @viaje.orden  #al borrar hay que reordenar los sitios del viaje
@resto_sitios = Viaje.where("orden > ?", @orden)
@viaje.destroy

@resto_sitios.each do |viaje|
 
viaje.update_attributes(:orden => @orden)
@orden = @orden+1
end
    respond_to do |format|
      format.html { redirect_to viajes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/viajes_helper.rb
module ViajesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html> 
<html> 
<head> 
  <title>Planet</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="planet"> 
  <div id="banner"> 
    <%= image_tag("logo3.png") %>
    <%= @page_title || "Planet Travel Site" %>
  </div> 
  <div id="columns"> 
    <div id="side"> 
      <%= link_to "Home", planet_index_path %><br /> 
      <%= link_to "Tipos",  types_path %><br /> 
      <%= link_to "Sitios", sites_path %><br /> 
      <%= link_to "Autores", planet_author_path %><br /> 
      <%= link_to "Contact", planet_contact_path %>
    </div> 
    <div id="main"> 
      <%= link_to('Home', planet_index_path) + " | " + link_to('Ejemplo', planet_ejemplo_path) + " | " + link_to('Autores', planet_author_path) + " | " + link_to('Contact', planet_contact_path) %><br />
      <%= yield %>
	  <br /><%= link_to('Home', planet_index_path) + " | " + link_to('Ejemplo', planet_ejemplo_path) + " | " + link_to('Autores', planet_author_path) + " | " + link_to('Contact', planet_contact_path) %><br />
    </div> 
  </div> 
</body> 
</html> 

app/views/planet/author.html.erb
<h1>Autores</h1><%= image_tag('roberto.jpg') %><p>Roberto Bermejo del Valle.</p><p>Correo electrónico: rober.bv@gmail.com</p><%= image_tag('pedro.png') %><p>Pedro García Chas.</p><p>Correo electrónico: pedro.garcia.chas@gmail.com</p>

app/views/planet/contact.html.erb
<h1>Contactar con Planet Travel Site</h1><p>Envienos un correo electrónico a:</p><p><a href="mailto:contact@planet.travel.com">         contact@planet.travel.com</a> </p><p>o llámenos al telefono: 615 783 567</p>

app/views/planet/ejemplo.html.erb
<h1>ERb: Extended Ruby</h1>
El formato ERb o .erb es HTML extendido con anotaciones Ruby, delimitadas por <strong> &lt% </strong> o <strong> &lt%= </strong> y <strong> %&gt </strong> , como en el siguiente ejemplo

<ul>
    <li> Anotación no visible: <%"esto NO se ve"%> </li>
    <li> Anotación visible: <%="esto SI se ve"%> </li>
    <li> Anotación no visible: <% t=Time.now%> </li>
    <li> Anotación visible: <%="hoy es:"+ t.to_s %> </li>
<ul>

También podemos generar un enlace al recurso (página) <strong> Home </strong> con el siguiente hiperenlace <%= link_to('Home',planet_index_path)%>

Rails ejecuta el código Ruby y lo inserta en la página HTML antes de generar la página.

app/views/planet/index.html.erb
<h1>Bienvenido</h1><p>This site gathers information of touristic sites from all over the world and should help you to organize your trips and your holidays.</p><%= image_tag('pedriza2-m.png') %><p>Feel free to use it for your convenience and pleasure.</p>

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <% types = Type.find(:all, :order => :name) %>
       <%= f.collection_select(:type_id, types, :id, :name) %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :zoom %><br />
    <%= f.text_field :zoom, value: "22" %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div id="site_list"> 
  <h1>Listing Sites</h1> 
 
  <table> 
  <% @sites.each do |site| %>
    <tr class="<%= cycle('list_line_odd', 'list_line_even') %>"> 
 
      <td> 
	  <% if site.image_url != "" %>
        	<%= link_to image_tag(site.image_url, :class => 'list_image'), site %>
	  <% end %>
      </td> 
 
      <td class="list_description"> 
        <dl> 
          <dt><%= link_to site.name, site %></dt> 
          <dd><%= truncate(strip_tags(site.description),
                 :length => 80) %></dd>
        </dl> 
      </td>
 
      <td class="list_actions"> 
        <%= link_to 'Show', site %><br/>
        <%= link_to 'Edit', edit_site_path(site) %><br/>
        <%= link_to 'Destroy', site, 
                    :confirm => 'Are you sure?',
                    :method => :delete %>
	  <%= form_for(@trip, remote: true) do |f| %>
	     <% f.number_field :trip_id, :value => 1, :hidden => true %>
           <% f.number_field :site_id, :value => site.id, :hidden => true %>
           <%= f.submit "Add site" %>
        <% end %>
      </td> 
    </tr> 
  <% end %>
  </table> 
</div> 
 
<br /> 
 
<%= link_to 'New site', new_site_path %>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<div id="site">
 
  <h1><b>Site: </b><%= @site.type.name if @site.type %></h1> 

  <%= image_tag(@site.image_url, :class => 'site_image') %>

  <h3><%= @site.name %></h3> 

  <p><%=sanitize @site.description %></p>

  <div class="position"> 
    <span>
      <b>Latitude:</b>
      <%= @site.latitude %>
    </span>
 
    <span>
       <b>Longitude:</b>
       <%= @site.longitude %>
    </span>
  </div> 
</div> 

<p />
<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<div id="site_list">
<h1>Listing types</h1>

<table>

<% @types.each do |type| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
       <td class="list_description">
         <dl>
           <dt><b><%= link_to type.name, 'types/'+type.id.to_s+'/sites' %></b></dt>
           <dd><%= truncate(strip_tags(type.description),
                              :length => 80) %></dd>
         </dl>
       </td>
   <!-- Acciones agrupadas en 1 celda en varias lineas -->
       <td class="list_actions">
         <%= link_to 'Show', type %> <br/>
         <%= link_to 'Edit', edit_type_path(type) %><br/>
         <%= link_to("Destroy", type, :confirm => "Are you sure?", :method => :delete) %>
       </td>
    </tr>
  <% end %>
  </table>
</div>


<br />

<b><%= link_to 'New Type', new_type_path %></b>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @type.description %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/viajes/_form.html.erb
<%= form_for(@viaje) do |f| %>
  <% if @viaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@viaje.errors.count, "error") %> prohibited this viaje from being saved:</h2>

      <ul>
      <% @viaje.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  
<%= hidden_field_tag(:"viaje[site_id]", @viaje.site_id) %>
<% @sitio = Site.find(@viaje.site_id) %>
<b><%= @sitio.name  %></b>
  <br />    

  </div>
 <%@prio = Viaje.find(:all, :select=>"orden") %>
<%= hidden_field_tag(:"viaje[orden_old]", @viaje.orden) %>
       <%= f.collection_select(:orden, @prio, :orden, :orden) %>
   orden

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/viajes/edit.html.erb
<h1>Editing viaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @viaje %> |
<%= link_to 'Back', viajes_path %>

app/views/viajes/index.html.erb
<h1>Listing viajes</h1>
<table>
  <tr>
    <th>Site</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @viajes.each do |viaje| %>
  <tr> <%sitio = Site.find(viaje.site_id) %>

<td><%= viaje.orden %></td>


    <td><%= sitio.name %></td>
    <td><%= link_to 'Show', viaje %></td>
    <td><%= link_to 'Change order', edit_viaje_path(viaje) %></td>
    <td><%= link_to 'Destroy', viaje, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

app/views/viajes/new.html.erb
<h1>New viaje</h1>

<%= render 'form' %>

<%= link_to 'Back', viajes_path %>

app/views/viajes/show.html.erb
<p id="notice"><%= notice %></p>

<div id="site">
  <h1><%= @sitio.name if @sitio.name %></h1>
  <%= image_tag(@sitio.image_url, :class => 'site_image') %>
  <h3><%= @sitio.name %></h3>
                 <!-- sanitize limpia virus, ... -->
  <p><%=sanitize @sitio.description %></p>
  <div class="position">
    <span>
       <b>Latitude:</b> <!-- en negrita (bold) -->
       <%= @sitio.latitude %>
    </span>
    <span>
        <b>Longitude:</b> <!-- en negrita (bold) -->
        <%= @sitio.longitude %>
    </span>
  </div>
</div>


<%= link_to 'Edit', edit_viaje_path(@viaje) %> |
<%= link_to 'Back', viajes_path %>